### ISSUE TITLE
audio "now playing" stuff missed in home screen

### ISSUE THREAD

**Issue by peppesr** [Nessus85100/Bello#50]
found that song cover and now playing tag are missing during music playback. take a look at the screenshot.
http://i58.tinypic.com/13zygz.jpg
Peppe

**Comment by Nessus85100** [comment]
It's not missed. I've change that since v3.0.0... https://github.com/Nessus85100/Bello/blob/master/changelog.txt#L21. Tired to see wrong aspect ratio thumbs there since XBMC can't set the proper thumb (poster/landscape/thumb) for the video type that was playing especially from video addons.

I know that the music part had no problems but since i've remove the video part i did the same for all media types for consistency reasons so the NowPlaying info to be the same across the whole skin..

Cheers
Nessus
